const initialPositionObj = {"00": {type: "r", color: "w"},
"01": {type: "n", color: "w"},
"02": {type: "b", color: "w"},
"03": {type: "q", color: "w"},
"04": {type: "k", color: "w"},
"05": {type: "b", color: "w"},
"06": {type: "n", color: "w"},
"07": {type: "r", color: "w"},
"10": {type: "p", color: "w"},
"11": {type: "p", color: "w"},
"12": {type: "p", color: "w"},
"13": {type: "p", color: "w"},
"14": {type: "p", color: "w"},
"15": {type: "p", color: "w"},
"16": {type: "p", color: "w"},
"17": {type: "p", color: "w"},
"20": null,
"21": null,
"22": null,
"23": null,
"24": null,
"25": null,
"26": null,
"27": null,
"30": null,
"31": null,
"32": null,
"33": null,
"34": null,
"35": null,
"36": null,
"37": null,
"40": null,
"41": null,
"42": null,
"43": null,
"44": null,
"45": null,
"46": null,
"47": null,
"50": null,
"51": null,
"52": null,
"53": null,
"54": null,
"55": null,
"56": null,
"57": null,
"60": {type: "p", color: "b"},
"61": {type: "p", color: "b"},
"62": {type: "p", color: "b"},
"63": {type: "p", color: "b"},
"64": {type: "p", color: "b"},
"65": {type: "p", color: "b"},
"66": {type: "p", color: "b"},
"67": {type: "p", color: "b"},
"70": {type: "r", color: "b"},
"71": {type: "n", color: "b"},
"72": {type: "b", color: "b"},
"73": {type: "q", color: "b"},
"74": {type: "k", color: "b"},
"75": {type: "b", color: "b"},
"76": {type: "n", color: "b"},
"77": {type: "r", color: "b"},
}

export default initialPositionObj